name: model-metrics
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Metrics

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |     
          echo "## Plots" >> report.md
          echo "###  Category image" >> report.md
          cml publish ./screenshots/category.png --md >> report.md
          echo "###  article word length" >> report.md
          cml publish ./screenshots/dist_article_word.png --md >> report.md
          # cat report.md
          cml send-comment report.md